Feature/bucket crud
sonr-io/sonr pull request #200
Opened 2022-04-19 12:43 UTC by Peyton232

2022-04-19 14:52 UTC, joshLong145 requested changes

2022-04-19 14:52 UTC, joshLong145 commented on highway/crud_object.go
> +			// Authenticator: &types.Authenticator{  //TODO this causes nil dereference, figure out why
should be hysrated with authenticator

2022-04-19 16:37 UTC, Peyton232 commented on highway/crud_object.go
> +			// Authenticator: &types.Authenticator{  //TODO this causes nil dereference, figure out why
what does hysrated mean?

2022-04-19 16:47 UTC, joshLong145 commented on highway/crud_object.go
> +			// Authenticator: &types.Authenticator{  //TODO this causes nil dereference, figure out why
cant spell, has been edited.

2022-04-20 00:10 UTC, joshLong145 approved these changes

2022-04-20 00:10 UTC, merged