Fix/did tests
sonr-io/sonr pull request #290
Opened 2022-05-06 20:07 UTC by joshLong145

## Changes
- tweaks to validation logic to allow for fragments in did urls,
- update to validator controller tests
- removal of fragments from did urls preventing parser to resolve due to invalid characters error
- removal of object tests as they depend on network IO

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [x] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-05-09 17:41 UTC, mcjcloud requested changes

2022-05-09 17:41 UTC, mcjcloud commented on pkg/did/did.go
> +		if strings.EqualFold(str, "did") || strings.EqualFold(str, "sonr") {
Why is this now "sonr"?

2022-05-09 17:41 UTC, mcjcloud commented on pkg/did/jwe_test.go
> +		// TODO: Add test cases.
No test cases

2022-05-09 17:41 UTC, mcjcloud commented on pkg/did/jwe_test.go
> +	type fields struct {
Why recreate the `Document` struct here?

2022-05-09 17:41 UTC, mcjcloud commented on pkg/did/jwe_test.go
> +		// TODO: Add test cases.
Same as above ^

2022-05-09 17:41 UTC, mcjcloud commented on pkg/did/jwe_test.go
> +				t.Errorf("Document.CreateJWS() error = %v, wantErr %v", err, tt.wantErr)
You don't actually compare the error you want with the one you got

2022-05-09 17:41 UTC, mcjcloud commented on x/registry/types/did.go
> +	baseDid, err := did.ParseDID(fmt.Sprintf("did:sonr:%s", strings.TrimPrefix(accountAddr, "sonr")))
Again, is `sonr` correct?

2022-05-09 17:43 UTC, joshLong145 commented on pkg/did/did.go
> +		if strings.EqualFold(str, "did") || strings.EqualFold(str, "sonr") {
this was a mistake, ill make this change. good catch

2022-05-09 17:58 UTC, joshLong145 commented on pkg/did/jwe_test.go
> +				t.Errorf("Document.CreateJWS() error = %v, wantErr %v", err, tt.wantErr)
good point

2022-05-09 17:59 UTC, joshLong145 commented on pkg/did/jwe_test.go
> +		// TODO: Add test cases.
good point

2022-05-09 18:02 UTC, joshLong145 commented on x/registry/types/did.go
> +	baseDid, err := did.ParseDID(fmt.Sprintf("did:sonr:%s", strings.TrimPrefix(accountAddr, "sonr")))
snr is correct after reviewing prads PR

2022-05-09 19:31 UTC, prnk28 commented on x/registry/types/did.go
> +	baseDid, err := did.ParseDID(fmt.Sprintf("did:sonr:%s", strings.TrimPrefix(accountAddr, "sonr")))
yes allows easiest namespace between wallet prefix and domain name

2022-05-09 19:57 UTC, joshLong145 commented
removed JWE related tests, will add back in in another PR after #295 merger

2022-05-09 20:35 UTC, prnk28 commented on x/registry/types/did.go
> +	baseDid, err := did.ParseDID(fmt.Sprintf("did:snr:%s", strings.TrimPrefix(accountAddr, "sonr")))
Need to fix this to be snr

2022-05-09 20:36 UTC, prnk28 commented on pkg/did/did_test.go
>  		id, err := ParseDID("did:sonr:123/path?query#fragment")
test string requires snr

2022-05-09 20:36 UTC, prnk28 commented on pkg/did/document_test.go
>  		if doc.Controller[0].String() != "did:sonr:123" {
Test needs to be changed to snr

2022-05-09 20:37 UTC, prnk28 requested changes
Test methods are still using `did:sonr` opposed to `did:snr`

2022-05-09 23:03 UTC, prnk28 approved these changes, later dismissed

2022-05-10 18:57 UTC, mcjcloud approved these changes

2022-05-10 19:18 UTC, ntindle approved these changes

2022-05-10 19:18 UTC, merged