WIP: Overall docs improvements
sonr-io/sonr pull request #348
Opened 2022-06-01 12:55 UTC by drgomesp

WIP

2022-06-01 14:48 UTC, joshLong145 requested changes
Left some comments.

2022-06-01 14:48 UTC, joshLong145 commented on docs/articles/fundamentals/network.md
> +and is the best option for quickly interacting with the Sonr network. Some of its capabilities are:
The wording of this section is a bit flawed. we start off by mentioning our blockchain layer. then transition onto functionalities of the motor. Perhaps we should think about the flow of this file as there is more to the stack than what is being outlined  in the  `Sonr Network` section. We should describe Sonr as a the Sum of our two node types `Motor` and `Highway` which themselves leverage our Blockchain layer.

2022-06-07 00:03 UTC, joshLong145 commented on docs/articles/fundamentals/network.md
> +and is the best option for quickly interacting with the Sonr network. Some of its capabilities are:
deleted my other comments as we can hide the pages for now. once we fix this wording up a little  and update i think its good to merge

2022-06-07 21:47 UTC, joshLong145 commented
Removed previous comments as they where no longer applicable after talking to others on those pages.

2022-06-08 12:37 UTC, ntindle commented on docs/articles/contributing/getting-started.md
> +
imo add it

2022-06-08 12:37 UTC, ntindle commented on docs/articles/contributing/guidelines.md
> +
imo keep it

2022-06-08 12:37 UTC, ntindle commented on docs/sidebars.js
> +      items: ['fundamentals/network', 'fundamentals/concepts'],
Don’t link to unfinished pages or make it clear they are unfinished

2022-06-23 15:33 UTC, closed without merging