Feature/jwk
sonr-io/sonr pull request #385
Opened 2022-06-17 13:29 UTC by joshLong145

- addition of jwk,jws, and jwe implementation for data encryption / decryption
## Changes

- Item 1
- Item 2

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-06-21 18:07 UTC, mcjcloud approved these changes

2022-06-21 19:14 UTC, prnk28 requested changes
`Internal/host` should not exist, please put this ipfs memory story inside the existing `pkg/host`

2022-06-21 20:03 UTC, joshLong145 commented
> `Internal/host` should not exist, please put this ipfs memory story inside the existing `pkg/host`

done, idk why that got commited.

2022-06-22 16:34 UTC, prdlk approved these changes

2022-06-22 16:34 UTC, merged