Feat/store refactoring
sonr-io/sonr pull request #476
Opened 2022-07-21 17:53 UTC by drgomesp

## Changes

- Item 1
- Item 2

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-07-22 20:41 UTC, joshLong145 commented on pkg/store/store.go
> +	storage.ReadableStorage
Do we need a wrapper interface for the store? i feel using the provided data stores should be suffcient

2022-07-27 19:11 UTC, drgomesp commented on pkg/protocol/ipfs_shell.go
> +func (i *IPFSShell) LookUpData(ctx context.Context, cid string, data interface{}) error {
We will remove this

2022-07-27 19:11 UTC, drgomesp commented on pkg/protocol/ipfs_shell.go
> +func (i *IPFSShell) PutData(ctx context.Context, data []byte) (string, error) {
Write small test case for checking if went through IPFS and failed at cache

2022-07-28 22:47 UTC, joshLong145 commented on internal/highway/x/protocol/ipfs_lite.go
> +
this can be removed

2022-07-28 22:54 UTC, joshLong145 reviewed
looking better, i still think we should be locking resources at a lower level than the interface implementations. If possible move the `i` mutex for the shell implementation to the store level  as we dont know when the cache will be hit if the defer unlocking of the resource will actually be at the correct time. and is also now up to the next implementor to make sure to lock resources if not at the store level.

2022-07-28 22:54 UTC, joshLong145 commented on internal/highway/x/protocol/ipfs_lite.go
> +	i.lock.Lock()
i still think the mutex belongs in the memory store layer. W should move `i` to memory store and lock in that layer

2022-07-28 22:54 UTC, joshLong145 commented on pkg/protocol/ipfs_shell.go
> +func (i *IPFSShell) LookUpData(ctx context.Context, cid string, data interface{}) error {
we should remove this method

2022-07-29 13:29 UTC, joshLong145 requested changes
Looking good, can we revert the go mod and go sun changes? We should handle migrating versions in another pr. Also see comment left inline.

2022-07-29 13:29 UTC, joshLong145 commented on pkg/protocol/ipfs_shell_test.go
> +const IPFSShellUrl = "localhost:5001"
Can we move this to a configurable option?

2022-07-29 17:07 UTC, drgomesp commented
@joshLong145 ready

2022-07-29 19:27 UTC, closed without merging

2022-07-29 21:39 UTC, ntindle commented
Don't force push to our repo.

2022-07-29 21:57 UTC, ntindle commented
Can you migrate the code into a branch without force pushing? It won't be able to merge to dev @drgomesp