Fix/motor issues
sonr-io/sonr pull request #575
Opened 2022-09-11 22:30 UTC by prnk28

## Changes

Fixes #573 #574 #572 
Connects

2022-09-11 22:40 UTC, ntindle approved these changes
I’d still use the constants for messages but that’s just me

2022-09-12 01:50 UTC, prnk28 commented
> I’d still use the constants for messages but that’s just me

Can go direct to logging on interface on the client during the loading process in UI. This way there is rational behind long lengths of time for account creation for now. @SCKelemen

2022-09-12 02:25 UTC, ma-sonr requested changes

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Initializing motor", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Requesting Airdrop for initial balance", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Creating shards for MPC", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Registering new DIDDocument for account", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Encrypting shards for Vault", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Setting up Account Vault", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Updating DIDDocument for Account", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/create_account.go
> +	mtr.callback.OnMotorEvent("Account registered successfully!", true)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/login.go
> +	mtr.callback.OnMotorEvent("Fetching shards from vault", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/login.go
> +	mtr.callback.OnMotorEvent("Reconstructing wallet", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/login.go
> +	mtr.callback.OnMotorEvent("Verifying with Blockchain", false)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 02:25 UTC, ma-sonr commented on pkg/motor/login.go
> +	mtr.callback.OnMotorEvent("Logged into account successfully!", true)
References to the value represented by each string should be made through some kind of strongly typed value / constant

2022-09-12 03:05 UTC, ma-sonr approved these changes

2022-09-12 03:05 UTC, ma-sonr approved these changes

2022-09-12 03:05 UTC, merged