update to proto comments for documentation
sonr-io/sonr pull request #662
Opened 2022-10-05 20:44 UTC by joshLong145

Update to protobuf comments for schemas
## Changes

- Item 1
- Item 2

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-10-05 20:58 UTC, mcjcloud requested changes
Looks like the spacing between properties is inconsistent; with some having a newline between properties and others not.

2022-10-05 20:58 UTC, mcjcloud commented on proto/motor/v1/request.proto
> +
no comment for this one?

2022-10-06 15:56 UTC, joshLong145 commented on proto/motor/v1/request.proto
> +
will add

2022-10-06 17:11 UTC, ntindle approved these changes
Much better

2022-10-06 20:57 UTC, mcjcloud approved these changes

2022-10-10 23:36 UTC, joshLong145 commented
Will be migrating this to the #655 branch

2022-10-21 21:19 UTC, prnk28 approved these changes

2022-10-21 22:07 UTC, merged