Add bucket tests to test suite
sonr-io/sonr pull request #709
Opened 2022-10-18 17:42 UTC by Oozyx

## Changes

- Refactor tests to run in a test suite

2022-10-18 18:37 UTC, joshLong145 approved these changes

2022-10-18 19:38 UTC, ntindle requested changes

2022-10-18 19:38 UTC, ntindle commented on internal/bucket/bucket_package_test.go
> +		Creator:    suite.motorNode.GetAddress(),
This test suite for buckets should also test
- Adding items to existing bucket
- Removing items from existing bucket
- Modifying items in a bucket
- Listing items in a bucket

2022-10-18 19:39 UTC, ntindle commented
Great job on getting the tests working

2022-10-19 14:35 UTC, joshLong145 commented on internal/bucket/bucket_package_test.go
> +		Creator:    suite.motorNode.GetAddress(),
to add a couple more
- adding a bucket to a bucket
- accessing a bucket from a bucket `resolveBuckets` will get all buckets at the top level of the single bucket this should be tested for respect to `bucketItems` that specify a bucket as a piece of content.

2022-10-20 21:39 UTC, ntindle approved these changes

2022-10-20 21:43 UTC, mcjcloud commented
Is this ready to merge?

2022-10-24 15:54 UTC, merged