updates to schema proto coments for docs
sonr-io/sonr pull request #731
Opened 2022-11-02 20:48 UTC by joshLong145

- Adds more comments for parsing into godocs in `schema` proto files

2022-11-02 21:05 UTC, mcjcloud approved these changes

2022-11-06 09:30 UTC, prnk28 requested changes
JS Style comments dont render in pkg.go.dev for our godoc, unsure if this will work can we test using protoc-doc-gen @ntindle ?

2022-11-14 19:18 UTC, joshLong145 commented
updated comment structure, to use single comment structure.

2022-11-18 20:30 UTC, prnk28 approved these changes

2023-03-31 21:53 UTC, closed without merging