Darshan/blok 105
sonr-io/sonr pull request #762
Opened 2022-11-15 18:08 UTC by lakshya-sky

## Changes

- Item 1
- Item 2

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-11-15 19:25 UTC, mcjcloud requested changes

2022-11-15 19:25 UTC, mcjcloud commented on pkg/client/account.go
> +		Coins:   []string{"120snr"},
Can you verify that the motor unit tests still work with this change? I believe this was bumped up as a workaround for something...

2022-11-15 19:25 UTC, mcjcloud commented on pkg/crypto/mpc/wallet.go
> +	configLength := reflect.ValueOf(w.Configs).MapKeys()
You shouldn't need to use reflection here,
```go
configLength := len(w.Configs)
```

2022-11-15 19:25 UTC, mcjcloud commented on pkg/did/internal/marshal/marshal.go
> +	//for _, normalizer := range normalizers {
Did you mean to leave this uncommented?

2022-11-15 19:25 UTC, mcjcloud commented on pkg/motor/login.go
> +	//if req.Password != "" {
Did you mean to leave this commented out? The request is not guaranteed to have a password provided so this check is important.

2022-11-15 19:25 UTC, mcjcloud commented on pkg/motor/login.go
> +	bankShard0, err := mpc.AesDecryptWithKey(req.AesPskKey, shards.ShardBank[0])
Decrypting all of these bank shards shouldn't be necessary. Providing just the two from above is enough to create the wallet.

2022-11-15 19:25 UTC, mcjcloud commented on pkg/motor/registry_test.go
> -func (suite *MotorTestSuite) Test_LoginWithKeys() {
Why was this removed?

2022-11-15 19:25 UTC, mcjcloud commented on pkg/motor/schema_test.go
> +/*
Why is this commented out?

2022-11-15 19:25 UTC, mcjcloud commented on pkg/motor/create_account.go
> +func (mtr *motorNodeImpl) CreateAccount(request mt.CreateAccountRequest, waitForVault bool) (mt.CreateAccountResponse, error) {
Take a look at `pkg/motor/connect_test.go` for how unit tests can be done without adding this test boolean.

2022-11-16 20:10 UTC, joshLong145 commented on pkg/motor/create_account.go
> +	r := make(chan int)
nit: we shouldn't make the channel unless its flagged to wait

2023-03-31 21:53 UTC, closed without merging